CREATE TABLE `event` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `id_mote` BIGINT(20) NOT NULL,
    `port` BIGINT(20) NOT NULL,
    `value` VARCHAR(22) NOT NULL,
    `gateway_time` DATETIME NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;