LUA_LPATH=/usr/share/lua/5.1

install:
	mkdir -p      $(LUA_LPATH)/tossam
	cp tossam.lua $(LUA_LPATH)
	cp codec.lua  $(LUA_LPATH)/tossam
	cp hdlc.lua   $(LUA_LPATH)/tossam
	cp serial.lua $(LUA_LPATH)/tossam
	cp sf.lua     $(LUA_LPATH)/tossam
